import type { Config } from 'tailwindcss'

// Design tokens from the Google Stitch "Engineered Precision" system (see DESIGN.md
// in the original export). Values are copied verbatim so the build matches the
// Stitch render; note the radius scale is intentionally shifted down one step
// from Tailwind's defaults (e.g. `rounded-full` is 0.75rem, not 9999px).
const sans = ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif']
const display = ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif']
const mono = ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace']

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#111318',
        'surface-dim': '#111318',
        'surface-bright': '#37393e',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low': '#1a1c20',
        'surface-container': '#1e2024',
        'surface-container-high': '#282a2e',
        'surface-container-highest': '#333539',
        'surface-variant': '#333539',
        'surface-tint': '#89ceff',
        background: '#111318',
        'on-background': '#e2e2e8',
        'on-surface': '#e2e2e8',
        'on-surface-variant': '#bec8d2',
        'inverse-surface': '#e2e2e8',
        'inverse-on-surface': '#2f3035',
        outline: '#88929b',
        'outline-variant': '#3e4850',
        primary: '#89ceff',
        'on-primary': '#00344d',
        'primary-container': '#0ea5e9',
        'on-primary-container': '#003751',
        'inverse-primary': '#006591',
        'primary-fixed': '#c9e6ff',
        'primary-fixed-dim': '#89ceff',
        'on-primary-fixed': '#001e2f',
        'on-primary-fixed-variant': '#004c6e',
        secondary: '#4edea3',
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        tertiary: '#7bd0ff',
        'on-tertiary': '#00354a',
        'tertiary-container': '#00a7e0',
        'on-tertiary-container': '#00384e',
        'tertiary-fixed': '#c4e7ff',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-tertiary-fixed': '#001e2c',
        'on-tertiary-fixed-variant': '#004c69',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
        margin: '2rem',
        'margin-mobile': '1.25rem',
        'margin-desktop': '3rem',
      },
      fontFamily: {
        'display-hero': display,
        'display-hero-mobile': display,
        'headline-lg': display,
        'headline-lg-mobile': display,
        'headline-md': display,
        'headline-sm': display,
        'body-lg': sans,
        'body-md': sans,
        'body-sm': sans,
        'label-ui': sans,
        'mono-code': mono,
        'mono-metric': mono,
        'label-caps': mono,
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-ui': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '500' }],
        'mono-code': ['13px', { lineHeight: '22px', letterSpacing: '0', fontWeight: '400' }],
        'mono-metric': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
